#! /bin/bash

function run {
    spring run *.groovy
}

function jar {
    spring jar ${appName}.jar .
}

function dockerBuild {
    spring jar ${appName}.jar . && docker-compose build
}

function dockerRun {
    spring jar ${appName}.jar . && docker-compose up --build
}

\$1
